### ISSUE TITLE
To-Do list before next phase

### ISSUE THREAD

**Issue by sharteeya** [sharteeya/ELF-Miner#4]
- [ ] Investigating the difference of ASM code that compiled by different compilers or different parameters.
- [ ] Redesign the process of behavior scanning.
- [ ] Redesign the way to describe behaviors in rules to reduce complexity.
- [ ] Add more testing cases and testing rules.
